export const AgencyAnalyticsActionTypes = {
	SET_THEME: "SET_THEME",
	SET_SELECTED_LOCATION: "SET_SELECTED_LOCATION",
	SET_LOCATION_DATA: "SET_LOCATION_DATA",
	ADD_PIN: "ADD_PIN",
	TOGGLE_TOUR_OPEN: "TOGGLE_TOUR_OPEN",
};
